---
# This playbook builds the .NET Website & creates a container --> pushes to the private repo and then pulls it down
- hosts: buildbox
  remote_user: GBBOSSDemo

  tasks: 
  - name: Restore the requirements
    command: dotnet restore
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux
  - name: .NET BUILD
    command: dotnet build
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux
  - name: Publish the site
    command: dotnet publish
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux

   #delete existing container, Build, Tag and Publish
  - name: Delete the existing DOCKER container
    command: docker image rm gbbossdemo/aspnet-core-linux
    become: true
    ignore_errors: true

  - name: Build the DOCKER image
    command: docker build -t gbbossdemo/aspnet-core-linux .
    become: true
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux

  - name: Tag the DOCKER image
    command: docker tag gbbossdemo/aspnet-core-linux gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Login to the Azure Private Registry
    command: docker login gbbossdemoregistry-microsoft.azurecr.io -u gbbossdemoregistry -p 4+=zpF4tpGL/pdKYhVXMy+b5jHX35P25
    become: true

  - name: Push to the Azure Private Registry
    command: docker push gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

#  - name: Tag the image
#    command: docker tag dansand71/aspnet-core-linux index.docker.io/dansand71/aspnet-core-linux
#    become: true

#  - name: Login to the Public Dansand71 Registry
#    command: docker login index.docker.io -u dansand71 -p Rockstar42!
#    become: true

#  - name: Push to the Dansand Public Registry
#    command: docker push index.docker.io/dansand71/aspnet-core-linux
#    become: true

- hosts: rhelrunners
  remote_user: GBBOSSDemo
  sudo : true 

  tasks: 
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: gbbossdemoregistry-microsoft.azurecr.io
      username: gbbossdemoregistry
      password: 4+=zpF4tpGL/pdKYhVXMy+b5jHX35P25
      reauthorize: yes

  - name: Kill the existing DOCKER container
    command: docker rm aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Kill the existing DOCKER Image
    command: docker rmi aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Pull the new DOCKER container
    command: docker pull gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Start the DOCKER container
    command: docker run -d -p 80:5000 --name=aspnet-core-linux gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Kill the existing AppInsights DOCKER container
    command: docker rm AppInsightMonitoring -f
    become: true
    ignore_errors: true

  - name: Start the monitoring container for Application Insights
    command: docker run -v /var/run/docker.sock:/docker.sock --name=AppInsightMonitoring -d microsoft/applicationinsights ikey=ab97398b-359e-4279-a819-88071a696de8 
    become: true
    ignore_errors: true
