---
# This playbook installs docker on all the hosts
- name: Install Docker
  hosts: rhelrunners
  remote_user: GBBOSSDemo
  sudo : true 


  tasks: 
  - name: update YUM
    yum: name=* state=latest

 - name: Get OMS Agent Executable
   get_url: 
      url: https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh
      dest: /etc/onboard_agent.sh
       
  - name: Install and Configure Agent
    shell: sudo sh /etc/onboard_agent.sh /
            -w 8db382ab-1870-4ae0-bc1d-d258c4b947a4 /
            -s l1X4hDSPK4HtdQ/OdqnqvWRdScgymqgUGrKCEshJMrT6ODaqiSAc3e98A1Fu0mP/7hYAdUA9xciutTnNdI8BfQ== /
            -d opinsights.azure.com
 
  # This playbook installs and configures all the items necessary for building out the demo's'  x3
  - name: remove the existing version of docker
    yum: name=docker state=absent
  - name: remove the existing selinux version of docker
    yum: name=docker-selinux state=absent
  - name: install the latest version of utils
    yum: name=yum-utils update_cache=yes state=latest
  - name: update newrepo for docker
    command: yum-config-manager --add-repo https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo
  - name: update repo cache for the new repo
    command: yum -q makecache fast
  - name: install the latest version of Docker
    yum: name=docker update_cache=yes state=latest
  - name: Install PIP
    easy_install:
      name: pip
      state: latest
  - name: install docker-py
    pip: name=docker-py version=1.9
  - name: Start docker
    service: 
      name: docker 
      state: running
