---
# This playbook builds the .NET Website & creates a container --> pushes to the private repo and then pulls it down
- hosts: buildbox
  remote_user: GBBOSSDemo

  tasks: 
  - name: Restore the requirements
    command: dotnet restore
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux
  - name: .NET BUILD
    command: dotnet build
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux
  - name: Publish the site
    command: dotnet publish
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux

   #delete existing container, Build, Tag and Publish
  - name: Delete the existing DOCKER container
    command: docker image rm gbbossdemo/aspnet-core-linux
    become: true
    ignore_errors: true
  - name: Delete the existing DOCKER image  - Save Space
    command: docker rmi [VAR1]gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux -f
    become: true
    ignore_errors: true
  - name: Delete the existing DOCKER registry image  - Save Space
    command: docker rmi gbbossdemo/aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Build the DOCKER image
    command: docker build -t gbbossdemo/aspnet-core-linux .
    become: true
    args:
      chdir: /source/OSSonAzure/sample-apps/aspnet-core-linux

  - name: Tag the DOCKER image
    command: docker tag gbbossdemo/aspnet-core-linux [VAR1]gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Login to the Azure Private Registry
    command: docker login [VAR1]gbbossdemoregistry-microsoft.azurecr.io -u [VAR1]gbbossdemoregistry -p [REPLACE-REGISTRY-PASSWORD]
    become: true

  - name: Push to the Azure Private Registry
    command: docker push [VAR1]gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

#Now deploy the containers on the worker nodes

- hosts: rhelrunners
  remote_user: GBBOSSDemo
  sudo : true 

  tasks: 
  - name: Log into private registry and force re-authorization
    docker_login:
      registry: [VAR1]gbbossdemoregistry-microsoft.azurecr.io
      username: [VAR1]gbbossdemoregistry
      password: [REPLACE-REGISTRY-PASSWORD]
      reauthorize: yes

  - name: Kill the existing DOCKER container
    command: docker rm aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Kill the existing DOCKER Image
    command: docker rmi aspnet-core-linux -f
    become: true
    ignore_errors: true

  - name: Pull the new DOCKER container
    command: docker pull [VAR1]gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Start the DOCKER container
    command: docker run -d -p 80:5000 --name=aspnet-core-linux [VAR1]gbbossdemoregistry-microsoft.azurecr.io/gbbossdemo/aspnet-core-linux
    become: true

  - name: Kill the existing AppInsights DOCKER container
    command: docker rm AppInsightMonitoring -f
    become: true
    ignore_errors: true

  - name: Start the monitoring container for Application Insights
    command: docker run -v /var/run/docker.sock:/docker.sock --name=AppInsightMonitoring -d microsoft/applicationinsights ikey=[REPLACE-APP-INSIGHTS-KEY] 
    become: true
    ignore_errors: true
